-- Weird & Wealthy — full database setup
--
-- Run these files IN ORDER in Supabase → SQL → New query:
--   1. supabase/01-schema-core.sql   (required — creates authors + posts)
--   2. supabase/02-storage.sql       (optional — image upload buckets)
--   3. supabase/03-create-admin.sql  (required — link your login to admin)
--
-- Do NOT run the admin insert until step 1 succeeds.
-- Check tables exist: select * from public.authors limit 1;
